### ISSUE TITLE
utils

### ISSUE THREAD

**Issue by flowerett** [rspective/voucherify-ruby-sdk#9]
Hi,
Can't see utils functions like in that implementations:
https://github.com/rspective/voucherify.js/blob/master/lib/voucherify.js#L210
or
https://github.com/rspective/voucherify-nodejs-sdk/blob/master/utils.js

do I need to implement it for my ruby backend client?

**Comment by pawelrychlik** [comment]
@flowerett thanks for reaching out. Utils functions are not ported to Ruby SDK yet. It would be great if you could contribute :) Otherwise, we'll probably cover that in the next days, anyway.

**Comment by pawelrychlik** [comment]
Delivered in https://github.com/rspective/voucherify-ruby-sdk/pull/10 and https://github.com/rspective/voucherify-ruby-sdk/pull/11
